name: Deploy to GitHub Pages

on:
  push:
    tags:
      - "v*"
      - "beta-*"

jobs:
  build_site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # NOTE: github does not ungzip your files so we zcat them to .json on
      # build/deploy. do the same thing in your dev environment
      - name: Clone KJVonly data
        run: |
          git clone --depth=1 https://github.com/kjvonly/data.git kjvdata
          mkdir static/data
          mv kjvdata/* static/data/
          cd static/data/json.gz
          for i in $(ls -1); do export f=${i%.gz} && zcat $i > $f ; done
          rm ./*.json.gz
          cd ../strongs.json.gz
          for i in $(ls -1 *.json.gz); do export f=${i%.gz} && zcat $i > $f ; done
          rm ./*.json.gz
          
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: build
        run: |
          npm run build

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          # this should match the `pages` option in your adapter-static options
          path: "build/"

  deploy:
    needs: build_site
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
